### ISSUE TITLE
Create graph implementation

### ISSUE THREAD

**Issue by fmcubium** [fmcubium/Starcrosser#1]
Create the graph implementation using an adjacency list.

The implementation should contain:

1.  A map that maps IDs to lists of IDs.
2.  A hashmap or vector of pairs (will probably be better) that maps strings to their respective IDs.

The implementation should be able to support a random access of nodes, and should be able to return a string given an ID.

**Comment by carsonful** [comment]
This issue was solved during the PR of Graph.h/cpp
