### ISSUE TITLE
Parse through star_adjacency.csv file to extract closest stars data

### ISSUE THREAD

**Issue by carsonful** [fmcubium/Starcrosser#7]
We need to implement a script or function to parse through the star_adjacency.csv file and extract the list of closest stars for each star in the dataset.

What particular ways would you want to organize this?

In my personal opinion we should use a csv library of some sort.
Ex. fast-cpp-csv-parser
https://github.com/ben-strasser/fast-cpp-csv-parser

**Comment by fmcubium** [comment]
That's fine, we can definitely use a library to parse the csv if it improves performance

**Comment by carsonful** [comment]
Issues solved with approval of PR.
